### ISSUE TITLE
Error installing build - user error?

### ISSUE THREAD

**Issue by altaurog** [software-jessies-org/jessies#46]
I am trying to build and install terminator on debian bullseye
I have openjdk-11 installed

When building, I get the warning: 
```
 No JDK 8 rt.jar found! 
 
 We'll build with -source to ensure language compatibility, 
 but without rt.jar this build can't guarantee API compatibility. 
 
 Be careful! 
```
Does this mean I need openjdk-8?

I didn't give it the root password for update-login-record, so make reports a build Error

When I try to run the terminator binary directly I get the following:
```
java.lang.NullPointerException
	at terminator.terminal.PtyProcess.updateLoginRecord(PtyProcess.java:255)
	at terminator.terminal.PtyProcess$1.call(PtyProcess.java:153)
	at terminator.terminal.PtyProcess$1.call(PtyProcess.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[Couldn't initialize terminal: NullPointerException.]
```

When I try installing with `sudo checkinstall -D make -C terminator install` I get this error:
```
make: Entering directory '/home/altaurog/build/jessies/terminator'
Traceback (most recent call last):
	1: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
<internal:gem_prelude>:1:in `require': Invalid argument @ rb_check_realpath_internal - /usr/lib/ruby/vendor_ruby/rubygems.rb (Errno::EINVAL)
make: *** [../salma-hayek/lib/build/simple.make:101: recurse] Error 1
make: Leaving directory '/home/altaurog/build/jessies/terminator'

****  Installation failed. Aborting package creation.
```
Any help here would be greatly appreciated

**Comment by martindorey** [comment]
> Does this mean I need openjdk-8?

No, just that anyone checking in changes that you might suggest would want to try them on Java 8 too.

> java.lang.NullPointerException
> 	at terminator.terminal.PtyProcess.updateLoginRecord(PtyProcess.java:255)

That line:

https://github.com/software-jessies-org/jessies/blob/f0ffa063b1cc255cfd2f984007e9e1dfec9bc7dd/terminator/src/terminator/terminal/PtyProcess.java#L255

... calls findSupportBinary, which might return null:

https://github.com/software-jessies-org/jessies/blob/f0ffa063b1cc255cfd2f984007e9e1dfec9bc7dd/salma-hayek/src/e/util/FileUtilities.java#L444

... in the situation you describe.  I've pushed a fix to make it just log a warning if the binary is missing.  Thanks for the good bug report.

> make: *** [../salma-hayek/lib/build/simple.make:101: recurse] Error 1

So:

https://github.com/software-jessies-org/jessies/blob/f0ffa063b1cc255cfd2f984007e9e1dfec9bc7dd/salma-hayek/lib/build/simple.make#L101

... runs what looks like a simple Ruby script:

https://github.com/software-jessies-org/jessies/blob/master/salma-hayek/lib/build/filter-build-output.rb

... without any gem magic.  (Why doesn't github's Search feature find filename matches?  Why doesn't the find file feature let me go into the salma-hayek/lib/build/ directory and why is it excluding matches from there?  Is "build" really a bad name for a directory containing makefiles and similar build scripts?)

You might be able to avoid it by doing something like:

`sudo checkinstall -D make -C terminator install echo.hello`

But how is eg:

https://github.com/software-jessies-org/jessies/blob/f0ffa063b1cc255cfd2f984007e9e1dfec9bc7dd/terminator/bin/terminator#L1

... going to work if that doesn't?  Ah, perhaps the ruby that's first in your PATH is broken but /usr/bin/ruby is fine.  Why are we explicitly invoking ruby rather than relying on the #! line?

https://github.com/software-jessies-org/jessies/commit/c2f25bc924c262a2ecd315746bdeeeeba64a8bce

I don't think we've had a Solaris build since 2014 and, if we started that up again, it looks like we wouldn't need the hack anyway, so I've taken it out, so it might just work for you now.  But don't you want the ruby that's first in your PATH to work?

I think that's addressed all three points, but I won't "Close with comment" before giving an opportunity for feedback, especially about the ruby that's first in the PATH.

**Comment by altaurog** [comment]
I hope to give this a whirl again today.  I am quite certain I only have one ruby, `/usr/bin/ruby`, as packaged by debian.  Is there a package missing that I need?
```
$ dpkg -l 'ruby*' | grep ^ii
ii  ruby                       1:2.7+2      amd64        Interpreter of object-oriented scripting language Ruby (default version)
ii  ruby-minitest              5.13.0-1     all          Ruby test tools supporting TDD, BDD, mocking, and benchmarking
ii  ruby-net-telnet            0.1.1-2      all          telnet client library
ii  ruby-power-assert          1.1.7-2      all          library showing values of variables and method calls in an expression
ii  ruby-rubygems              3.2.5-2      all          Package management framework for Ruby
ii  ruby-test-unit             3.3.9-1      all          unit testing framework for Ruby
ii  ruby-xmlrpc                0.3.0-2      all          XMLRPC library for Ruby
ii  ruby2.7                    2.7.2-4      amd64        Interpreter of object-oriented scripting language Ruby
ii  rubygems-integration       1.18         all          integration of Debian Ruby packages with Rubygems
$ which ruby
/usr/bin/ruby
$ alias ruby
bash: alias: ruby: not found
$ declare -f ruby || echo no ruby function
no ruby function
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
$ /usr/bin/ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
```

**Comment by martindorey** [comment]
What am I on about, with this ruby first in your PATH?  It would need to first in the PATH under sudo.  That’d explain why it doesn’t go wrong all the time.  I’m betting, though, that the “one ruby” claim applies just as much to root.  I don’t see anything wrong or missing in those Ruby packages.  A Google for gem_prelude does find quite a few instances of people who’ve seen similar with other scripts.  The only commonality seems to be that they have something wrong with their Ruby installation... but I couldn’t tell you what.

**Comment by altaurog** [comment]
Yes, now terminator runs, but still problems with ruby, as you predicted.  This is the debian-packed ruby, it is a fresh install of debian bullseye.  A symbolic link from `~/bin/terminator` seems to work so I’ll just forego installation and use that for now.  (A hard link doesn’t work, I get a similar ruby error).
Many thanks for your help.

**Comment by martindorey** [comment]
I wonder if it’s something to do with https://wiki.debian.org/CheckInstall - I’d not heard of that before.  Turning an autotools “make install” into a .deb is clever, but our install target, https://github.com/software-jessies-org/jessies/blob/f0ffa063b1cc255cfd2f984007e9e1dfec9bc7dd/salma-hayek/lib/build/universal.make#L1026, isn’t like an autotools one.  It builds a .deb and installs it.  If you, quite reasonably, don’t like typing your password into a sudo that our makefile ran, then perhaps you’d be better off with “make installer”.  Then you could find the .deb and do the sudo dpkg -i yourself.

**Comment by martindorey** [comment]
I just tried “sudo checkinstall -D make -C terminator install” for the first time on my Debian Stretch box.  After quite a bit of interaction, it created and installed a package, which it decided to call “work”, but the package contained nothing from Terminator, just some build detritus like rpmdb files and some documentation that checkinstall had confabulated.  Our underlying Terminator package got installed too.  That seems to work, far as I can easily tell from my phone.  I certainly saw no mysterious Ruby errors during building, so it’s probably not very persuasive, but I’m more confident more that checkinstall won’t be helpful here.

**Comment by altaurog** [comment]
haha, okay.  I will try just make installer, which sound like what I want, but I venture there’ll be problems from ruby.  I don’t know much when it comes to ruby, unfortunately, and I didn’t find the google results very helpful.

**Comment by altaurog** [comment]
`make installer` still is prompting me for sudo password.  (I don’t know why I’m so against this, I mean I’ve been typing my password into terminator every time I run sudo for years, so obviously I trust your software.  Why shouldn’t I trust your build?)
I tried `NEEDS_SETUID.Linux = ""` in per-directory.make, but that didn’t help.  So I commented out the LOCAL_LDFLAGS line just thereafter, where the `sudo chmod` is invoked.
Evergreen package is built.  I had to remove `terminator/.generated/build-revision.txt.tmp`, which was owned by root, and install `alien`.  Terminator package is also built.  I installed it and it works!
BTW the build seems to have left these in my homedir:
```
rpmbuild/
rpmbuild/BUILD
rpmbuild/SRPMS
rpmbuild/BUILDROOT
```
Overall this was pretty painless, and I very much appreciate the help.  Closing this, but perhaps you’d consider signing your releases to save other paranoid folks like me a bit of time?
